### ISSUE TITLE
你好请问默认怎么挂载CFS磁盘的

### ISSUE THREAD

**Issue by 377123** [TencentCloudBase-Marketplace/Discuz-Q#1]
你好请问默认怎么挂载CFS磁盘的

**Comment by binggg** [comment]
可以看下这两处配置
https://github.com/TencentCloudBase-Marketplace/Discuz-Q/blob/master/cloudbaserc.json#L27
https://github.com/TencentCloudBase-Marketplace/Discuz-Q/blob/master/cloudbaserc.json#L33

具体的文档可以参考 CloudBase Framework的文档

配置应用依赖 CFS
https://docs.cloudbase.net/framework/config.html#requirement-addons
容器插件挂载数据卷
https://docs.cloudbase.net/framework/plugins/framework-plugin-container.html#volumemounts
