### ISSUE TITLE
点击 部署按钮  都填完无法点完成 请问是怎么了

### ISSUE THREAD

**Issue by 377123** [TencentCloudBase-Marketplace/Discuz-Q#3]
![image](https://user-images.githubusercontent.com/4208764/101886639-bfb0b080-3bd6-11eb-9abc-27b679614307.png)

**Comment by binggg** [comment]
可以检查下密码是否按照要求填写正确

**Comment by 377123** [comment]
确实是密码的问题。  
不过我修后执行失败了

![image](https://user-images.githubusercontent.com/4208764/102037781-94a9a500-3e00-11eb-9dee-c98340681e74.png)

**Comment by WilsonLiu95** [comment]
看下是不是环境下http访问服务内，根路径是不是已有占用了
