### ISSUE TITLE
请问 tcb 命令提示如下是怎么了

### ISSUE THREAD

**Issue by 377123** [TencentCloudBase-Marketplace/Discuz-Q#4]
![image](https://user-images.githubusercontent.com/4208764/101887249-8dec1980-3bd7-11eb-807d-ba77f90310fd.png)

**Comment by binggg** [comment]
上一个版本在构建中了，可以发一下环境id

**Comment by 377123** [comment]
dzq-4gxpo81p679f7f65

**Comment by binggg** [comment]
腾讯云账户的uin 发一下，搜环境id没找到
