### ISSUE TITLE
提示密码错误  怎么上传到 docker.io吗

### ISSUE THREAD

**Issue by 377123** [TencentCloudBase-Marketplace/Discuz-Q#5]
chengyun:Discuz-Q ring$ sh ./run v1.0.1
-------------------复制仓库源码--------------------
-------------------准备生成Discuz!Q--------------------
-------------------生成本地镜像 v1.0.1--------------------
[+] Building 15.0s (10/10) FINISHED                                                                                     
 => [internal] load .dockerignore                                                                                  0.2s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.2s
 => => transferring dockerfile: 1.00kB                                                                             0.1s
 => [internal] load metadata for docker.io/library/ubuntu:focal                                                    0.0s
 => [1/5] FROM docker.io/library/ubuntu:focal                                                                      0.0s
 => [internal] load build context                                                                                  5.1s
 => => transferring context: 26.30MB                                                                               4.4s
 => CACHED [2/5] RUN apt-get update --no-install-recommends &&      apt-get install -y --no-install-recommends tz  0.0s
 => [3/5] COPY root /                                                                                              2.0s
 => [4/5] RUN chown -R www-data:www-data /var/www/discuz                                                           4.8s
 => [5/5] RUN curl https://discuzq-docs-1258344699.cos.ap-guangzhou.myqcloud.com/setup.php -o /usr/sbin/setup.php  1.7s
 => exporting to image                                                                                             1.0s
 => => exporting layers                                                                                            1.0s
 => => writing image sha256:ce019bd33f29ae58bbe23d73f9ac9ed7e1d93cb9d27519d22ef3b13865e30bfd                       0.0s 
 => => naming to docker.io/tcb-53623075-bkfo/discuzq:v1.0.1                                                        0.0s
-------------------上传镜像到云托管镜像仓库--------------------
Password:
Sorry, try again.

**Comment by WilsonLiu95** [comment]
https://docs.cloudbase.net/run/create-service.html#guan-li-jing-xiang-cang-ku
